FROM arm32v7/node:14.19

# Sets the current dir as this one
WORKDIR /usr/src/app

# Copies the project over to the image
COPY . .

# Exposes port 8888
EXPOSE 8888

# Installs dependencies
RUN npm install --production

# Runs pkg
RUN tar cvf - build/* package.json node_modules/* assets/* README.md | gzip > ./tcore-plugin-raspberry-arm7-pi-gpio-v0.3.2.tcore
