import { DatabaseModule } from "@tago-io/tcore-sdk";
import configs from "./settings";
import addDeviceData from "./Providers/DeviceData/addDeviceData";
import editDeviceData from "./Providers/DeviceData/editDeviceData";
import createAction from "./Providers/Action/createAction";
import createAnalysis from "./Providers/Analysis/createAnalysis";
import createDevice from "./Providers/Device/createDevice";
import createDeviceToken from "./Providers/Device/createDeviceToken";
import deleteAction from "./Providers/Action/deleteAction";
import deleteAnalysis from "./Providers/Analysis/deleteAnalysis";
import deleteAnalysisLogs from "./Providers/Analysis/deleteAnalysisLogs";
import deleteDevice from "./Providers/Device/deleteDevice";
import deleteDeviceParam from "./Providers/Device/deleteDeviceParam";
import deleteDeviceToken from "./Providers/Device/deleteDeviceToken";
import editAction from "./Providers/Action/editAction";
import editAnalysis from "./Providers/Analysis/editAnalysis";
import editDevice from "./Providers/Device/editDevice";
import getActionInfo from "./Providers/Action/getActionInfo";
import getActionList from "./Providers/Action/getActionList";
import getAnalysisInfo from "./Providers/Analysis/getAnalysisInfo";
import getAnalysisList from "./Providers/Analysis/getAnalysisList";
import getDeviceDataDefaultQ from "./Providers/DeviceData/getDeviceDataDefaultQ";
import getDeviceDataAmount from "./Providers/DeviceData/getDeviceDataAmount";
import getDeviceByToken from "./Providers/Device/getDeviceByToken";
import getDeviceInfo from "./Providers/Device/getDeviceInfo";
import getDeviceList from "./Providers/Device/getDeviceList";
import getDeviceParamList from "./Providers/Device/getDeviceParamList";
import getDeviceTokenList from "./Providers/Device/getDeviceTokenList";
import getPluginStorageItem from "./Providers/PluginStorage/getPluginStorageItem";
import getSummary from "./Providers/Summary/getSummary";
import deletePluginStorageItem from "./Providers/PluginStorage/deletePluginStorageItem";
import setDeviceParams from "./Providers/Device/setDeviceParams";
import { destroyKnex, setupKnex } from "./Database";
import getTagKeys from "./Providers/Tag/getTagKeys";
import addStatistic from "./Providers/Statistic/addStatistics";
import getHourlyStatistics from "./Providers/Statistic/getHourlyStatistics";
import emptyDevice from "./Providers/Device/emptyDevice";
import getDeviceDataLastValue from "./Providers/DeviceData/getDeviceDataLastValue";
import getDeviceDataLastLocation from "./Providers/DeviceData/getDeviceDataLastLocation";
import getDeviceDataLastItem from "./Providers/DeviceData/getDeviceDataLastItem";
import getDeviceDataLastInsert from "./Providers/DeviceData/getDeviceDataLastInsert";
import getDeviceDataFirstValue from "./Providers/DeviceData/getDeviceDataFirstValue";
import getDeviceDataFirstLocation from "./Providers/DeviceData/getDeviceDataFirstLocation";
import getDeviceDataFirstItem from "./Providers/DeviceData/getDeviceDataFirstItem";
import getDeviceDataFirstInsert from "./Providers/DeviceData/getDeviceDataFirstInsert";
import getDeviceDataCount from "./Providers/DeviceData/getDeviceDataCount";
import getDeviceDataMax from "./Providers/DeviceData/getDeviceDataMax";
import getDeviceDataMin from "./Providers/DeviceData/getDeviceDataMin";
import getDeviceDataAvg from "./Providers/DeviceData/getDeviceDataAvg";
import getDeviceDataSum from "./Providers/DeviceData/getDeviceDataSum";
import addAnalysisLog from "./Providers/Analysis/addAnalysisLog";
import getAnalysisLogs from "./Providers/Analysis/getAnalysisLogs";
import deleteDeviceData from "./Providers/DeviceData/deleteDeviceData";
import setPluginStorageItem from "./Providers/PluginStorage/setPluginStorageItem";
import getAllPluginStorageItems from "./Providers/PluginStorage/getAllPluginStorageItem";
import getAccountAmount from "./Providers/Account/getAccountAmount";
import getAccountByToken from "./Providers/Account/getAccountByToken";
import getAccountByUsername from "./Providers/Account/getAccountByUsername";
import getAccountInfo from "./Providers/Account/getAccountInfo";
import getAccountList from "./Providers/Account/getAccountList";
import getAccountToken from "./Providers/Account/getAccountToken";
import getDeviceToken from "./Providers/Device/getDeviceToken";
import createAccount from "./Providers/Account/createAccount";
import createAccountToken from "./Providers/Account/createAccountToken";
import applyDeviceDataRetention from "./Providers/DeviceData/applyDeviceDataRetention";

export const mySQL = new DatabaseModule({
  id: "mysql",
  name: "MySQL",
  configs,
});

mySQL.onLoad = setupKnex;
mySQL.onDestroy = destroyKnex;

mySQL.addAnalysisLog = addAnalysisLog;
mySQL.addDeviceData = addDeviceData;
mySQL.addStatistic = addStatistic;
mySQL.applyDeviceDataRetention = applyDeviceDataRetention;
mySQL.createAccount = createAccount;
mySQL.createAccountToken = createAccountToken;
mySQL.createAction = createAction;
mySQL.createAnalysis = createAnalysis;
mySQL.createDevice = createDevice;
mySQL.createDeviceToken = createDeviceToken;
mySQL.deleteAction = deleteAction;
mySQL.deleteAnalysis = deleteAnalysis;
mySQL.deleteAnalysisLogs = deleteAnalysisLogs;
mySQL.deleteDevice = deleteDevice;
mySQL.deleteDeviceData = deleteDeviceData;
mySQL.deleteDeviceParam = deleteDeviceParam;
mySQL.deleteDeviceToken = deleteDeviceToken;
mySQL.deletePluginStorageItem = deletePluginStorageItem;
mySQL.editAction = editAction;
mySQL.editAnalysis = editAnalysis;
mySQL.editDevice = editDevice;
mySQL.editDeviceData = editDeviceData;
mySQL.emptyDevice = emptyDevice;
mySQL.getAccountAmount = getAccountAmount;
mySQL.getAccountByToken = getAccountByToken;
mySQL.getAccountByUsername = getAccountByUsername;
mySQL.getAccountInfo = getAccountInfo;
mySQL.getAccountList = getAccountList;
mySQL.getAccountToken = getAccountToken;
mySQL.getActionInfo = getActionInfo;
mySQL.getActionList = getActionList;
mySQL.getAllPluginStorageItems = getAllPluginStorageItems;
mySQL.getAnalysisInfo = getAnalysisInfo;
mySQL.getAnalysisList = getAnalysisList;
mySQL.getAnalysisLogs = getAnalysisLogs;
mySQL.getDeviceByToken = getDeviceByToken;
mySQL.getDeviceDataAmount = getDeviceDataAmount;
mySQL.getDeviceDataAvg = getDeviceDataAvg;
mySQL.getDeviceDataCount = getDeviceDataCount;
mySQL.getDeviceDataDefaultQ = getDeviceDataDefaultQ;
mySQL.getDeviceDataFirstInsert = getDeviceDataFirstInsert;
mySQL.getDeviceDataFirstItem = getDeviceDataFirstItem;
mySQL.getDeviceDataFirstLocation = getDeviceDataFirstLocation;
mySQL.getDeviceDataFirstValue = getDeviceDataFirstValue;
mySQL.getDeviceDataLastInsert = getDeviceDataLastInsert;
mySQL.getDeviceDataLastItem = getDeviceDataLastItem;
mySQL.getDeviceDataLastLocation = getDeviceDataLastLocation;
mySQL.getDeviceDataLastValue = getDeviceDataLastValue;
mySQL.getDeviceDataMax = getDeviceDataMax;
mySQL.getDeviceDataMin = getDeviceDataMin;
mySQL.getDeviceDataSum = getDeviceDataSum;
mySQL.getDeviceInfo = getDeviceInfo;
mySQL.getDeviceList = getDeviceList;
mySQL.getDeviceParamList = getDeviceParamList;
mySQL.getDeviceToken = getDeviceToken;
mySQL.getDeviceTokenList = getDeviceTokenList;
mySQL.getHourlyStatistics = getHourlyStatistics;
mySQL.getPluginStorageItem = getPluginStorageItem;
mySQL.getSummary = getSummary;
mySQL.getTagKeys = getTagKeys;
mySQL.setDeviceParams = setDeviceParams;
mySQL.setPluginStorageItem = setPluginStorageItem;
