import { DatabaseModule } from "@tago-io/tcore-sdk";
import { destroyKnex, setupKnex } from "./Database/index.ts";
import createAccount from "./Providers/Account/createAccount.ts";
import createAccountToken from "./Providers/Account/createAccountToken.ts";
import getAccountAmount from "./Providers/Account/getAccountAmount.ts";
import getAccountByToken from "./Providers/Account/getAccountByToken.ts";
import getAccountByUsername from "./Providers/Account/getAccountByUsername.ts";
import getAccountInfo from "./Providers/Account/getAccountInfo.ts";
import getAccountList from "./Providers/Account/getAccountList.ts";
import getAccountToken from "./Providers/Account/getAccountToken.ts";
import createAction from "./Providers/Action/createAction.ts";
import deleteAction from "./Providers/Action/deleteAction.ts";
import editAction from "./Providers/Action/editAction.ts";
import getActionInfo from "./Providers/Action/getActionInfo.ts";
import getActionList from "./Providers/Action/getActionList.ts";
import addAnalysisLog from "./Providers/Analysis/addAnalysisLog.ts";
import createAnalysis from "./Providers/Analysis/createAnalysis.ts";
import deleteAnalysis from "./Providers/Analysis/deleteAnalysis.ts";
import deleteAnalysisLogs from "./Providers/Analysis/deleteAnalysisLogs.ts";
import editAnalysis from "./Providers/Analysis/editAnalysis.ts";
import getAnalysisInfo from "./Providers/Analysis/getAnalysisInfo.ts";
import getAnalysisList from "./Providers/Analysis/getAnalysisList.ts";
import getAnalysisLogs from "./Providers/Analysis/getAnalysisLogs.ts";
import createDevice from "./Providers/Device/createDevice.ts";
import createDeviceToken from "./Providers/Device/createDeviceToken.ts";
import deleteDevice from "./Providers/Device/deleteDevice.ts";
import deleteDeviceParam from "./Providers/Device/deleteDeviceParam.ts";
import deleteDeviceToken from "./Providers/Device/deleteDeviceToken.ts";
import editDevice from "./Providers/Device/editDevice.ts";
import emptyDevice from "./Providers/Device/emptyDevice.ts";
import getDeviceByToken from "./Providers/Device/getDeviceByToken.ts";
import getDeviceInfo from "./Providers/Device/getDeviceInfo.ts";
import getDeviceList from "./Providers/Device/getDeviceList.ts";
import getDeviceParamList from "./Providers/Device/getDeviceParamList.ts";
import getDeviceToken from "./Providers/Device/getDeviceToken.ts";
import getDeviceTokenList from "./Providers/Device/getDeviceTokenList.ts";
import setDeviceParams from "./Providers/Device/setDeviceParams.ts";
import addDeviceData from "./Providers/DeviceData/addDeviceData.ts";
import applyDeviceDataRetention from "./Providers/DeviceData/applyDeviceDataRetention.ts";
import deleteDeviceData from "./Providers/DeviceData/deleteDeviceData.ts";
import editDeviceData from "./Providers/DeviceData/editDeviceData.ts";
import getDeviceDataAmount from "./Providers/DeviceData/getDeviceDataAmount.ts";
import getDeviceDataAvg from "./Providers/DeviceData/getDeviceDataAvg.ts";
import getDeviceDataCount from "./Providers/DeviceData/getDeviceDataCount.ts";
import getDeviceDataDefaultQ from "./Providers/DeviceData/getDeviceDataDefaultQ.ts";
import getDeviceDataFirstInsert from "./Providers/DeviceData/getDeviceDataFirstInsert.ts";
import getDeviceDataFirstItem from "./Providers/DeviceData/getDeviceDataFirstItem.ts";
import getDeviceDataFirstLocation from "./Providers/DeviceData/getDeviceDataFirstLocation.ts";
import getDeviceDataFirstValue from "./Providers/DeviceData/getDeviceDataFirstValue.ts";
import getDeviceDataLastInsert from "./Providers/DeviceData/getDeviceDataLastInsert.ts";
import getDeviceDataLastItem from "./Providers/DeviceData/getDeviceDataLastItem.ts";
import getDeviceDataLastLocation from "./Providers/DeviceData/getDeviceDataLastLocation.ts";
import getDeviceDataLastValue from "./Providers/DeviceData/getDeviceDataLastValue.ts";
import getDeviceDataMax from "./Providers/DeviceData/getDeviceDataMax.ts";
import getDeviceDataMin from "./Providers/DeviceData/getDeviceDataMin.ts";
import getDeviceDataSum from "./Providers/DeviceData/getDeviceDataSum.ts";
import deletePluginStorageItem from "./Providers/PluginStorage/deletePluginStorageItem.ts";
import getAllPluginStorageItems from "./Providers/PluginStorage/getAllPluginStorageItem.ts";
import getPluginStorageItem from "./Providers/PluginStorage/getPluginStorageItem.ts";
import setPluginStorageItem from "./Providers/PluginStorage/setPluginStorageItem.ts";
import addStatistic from "./Providers/Statistic/addStatistics.ts";
import getHourlyStatistics from "./Providers/Statistic/getHourlyStatistics.ts";
import getSummary from "./Providers/Summary/getSummary.ts";
import getTagKeys from "./Providers/Tag/getTagKeys.ts";
import configs from "./settings.ts";

export const mySQL = new DatabaseModule({
  id: "mysql",
  name: "MySQL",
  configs,
});

mySQL.onLoad = setupKnex;
mySQL.onDestroy = destroyKnex;

mySQL.addAnalysisLog = addAnalysisLog;
mySQL.addDeviceData = addDeviceData;
mySQL.addStatistic = addStatistic;
mySQL.applyDeviceDataRetention = applyDeviceDataRetention;
mySQL.createAccount = createAccount;
mySQL.createAccountToken = createAccountToken;
mySQL.createAction = createAction;
mySQL.createAnalysis = createAnalysis;
mySQL.createDevice = createDevice;
mySQL.createDeviceToken = createDeviceToken;
mySQL.deleteAction = deleteAction;
mySQL.deleteAnalysis = deleteAnalysis;
mySQL.deleteAnalysisLogs = deleteAnalysisLogs;
mySQL.deleteDevice = deleteDevice;
mySQL.deleteDeviceData = deleteDeviceData;
mySQL.deleteDeviceParam = deleteDeviceParam;
mySQL.deleteDeviceToken = deleteDeviceToken;
mySQL.deletePluginStorageItem = deletePluginStorageItem;
mySQL.editAction = editAction;
mySQL.editAnalysis = editAnalysis;
mySQL.editDevice = editDevice;
mySQL.editDeviceData = editDeviceData;
mySQL.emptyDevice = emptyDevice;
mySQL.getAccountAmount = getAccountAmount;
mySQL.getAccountByToken = getAccountByToken;
mySQL.getAccountByUsername = getAccountByUsername;
mySQL.getAccountInfo = getAccountInfo;
mySQL.getAccountList = getAccountList;
mySQL.getAccountToken = getAccountToken;
mySQL.getActionInfo = getActionInfo;
mySQL.getActionList = getActionList;
mySQL.getAllPluginStorageItems = getAllPluginStorageItems;
mySQL.getAnalysisInfo = getAnalysisInfo;
mySQL.getAnalysisList = getAnalysisList;
mySQL.getAnalysisLogs = getAnalysisLogs;
mySQL.getDeviceByToken = getDeviceByToken;
mySQL.getDeviceDataAmount = getDeviceDataAmount;
mySQL.getDeviceDataAvg = getDeviceDataAvg;
mySQL.getDeviceDataCount = getDeviceDataCount;
mySQL.getDeviceDataDefaultQ = getDeviceDataDefaultQ;
mySQL.getDeviceDataFirstInsert = getDeviceDataFirstInsert;
mySQL.getDeviceDataFirstItem = getDeviceDataFirstItem;
mySQL.getDeviceDataFirstLocation = getDeviceDataFirstLocation;
mySQL.getDeviceDataFirstValue = getDeviceDataFirstValue;
mySQL.getDeviceDataLastInsert = getDeviceDataLastInsert;
mySQL.getDeviceDataLastItem = getDeviceDataLastItem;
mySQL.getDeviceDataLastLocation = getDeviceDataLastLocation;
mySQL.getDeviceDataLastValue = getDeviceDataLastValue;
mySQL.getDeviceDataMax = getDeviceDataMax;
mySQL.getDeviceDataMin = getDeviceDataMin;
mySQL.getDeviceDataSum = getDeviceDataSum;
mySQL.getDeviceInfo = getDeviceInfo;
mySQL.getDeviceList = getDeviceList;
mySQL.getDeviceParamList = getDeviceParamList;
mySQL.getDeviceToken = getDeviceToken;
mySQL.getDeviceTokenList = getDeviceTokenList;
mySQL.getHourlyStatistics = getHourlyStatistics;
mySQL.getPluginStorageItem = getPluginStorageItem;
mySQL.getSummary = getSummary;
mySQL.getTagKeys = getTagKeys;
mySQL.setDeviceParams = setDeviceParams;
mySQL.setPluginStorageItem = setPluginStorageItem;
