import fs from "node:fs";
import path from "node:path";

// lists all files in the icons folder
const files = fs.readdirSync(path.join(__dirname, "../assets/icons"));

// we will insert the enum into this file
const outputPath = path.join(__dirname, "../src/Components/Icon/Icon.types.ts");

const template = [
  "/* eslint-disable prettier/prettier */",
  "",
  "// ! This file is automatically generated. Please don't change it.",
  "",
  "/**",
  " * Types of icons available in the system.",
  " * Each one must match the corresponding filename in the /assets/icons folder.",
  " */",
  "enum EIcon {",
  files
    .filter((x) => !x.startsWith(".")) // can't start with a dot
    .map((x) => `  "${x.replace(".svg", "")}" = "${x.replace(".svg", "")}",`) // map the output to be an enum field
    .join("\n"), // join and break lines,
  "}",
  "",
  "const icons = {",
  files
    .filter((x) => !x.startsWith(".")) // can't start with a dot
    .map((x) => `  "${x.replace(".svg", "")}": import("../../../assets/icons/${x}"),`) // map the output to be an enum field
    .join("\n"),
  "}",
  "",
  "export { EIcon, icons };",
  "",
].join("\n");

// writes the enum string to the file
fs.writeFileSync(outputPath, template, { encoding: "utf-8" });
