import fs from "fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __filename = fileURLToPath(import.meta.url);
const dirname_ = dirname(__filename);

// lists all files in the icons folder
const files = fs.readdirSync(join(dirname_, "../assets/icons"));

// we will insert the enum into this file
const outputPath = join(dirname_, "../src/Components/Icon/Icon.types.ts");

const template = [
  "/* eslint-disable prettier/prettier */",
  "",
  "// ! This file is automatically generated. Please don't change it.",
  "",
  "/**",
  " * Types of icons available in the system.",
  " * Each one must match the corresponding filename in the /assets/icons folder.",
  " */",
  "enum EIcon {",
  files
    .filter((x) => !x.startsWith(".")) // can't start with a dot
    .map((x) => `  "${x.replace(".svg", "")}" = "${x.replace(".svg", "")}",`) // map the output to be an enum field
    .join("\n"), // join and break lines,
  "}",
  "",
  "const icons = {",
  files
    .filter((x) => !x.startsWith(".")) // can't start with a dot
    .map(
      (x) =>
        `  "${x.replace(".svg", "")}": lazy(() => ("../../../assets/icons/${x}")),`,
    ) // map the output to be an enum field
    .join("\n"),
  "}",
  "",
  "export { EIcon, icons };",
  "",
].join("\n");

// writes the enum string to the file
fs.writeFileSync(outputPath, template, { encoding: "utf-8" });
